apiVersion: v1
kind: ConfigMap
metadata:
  name: eno-ws-config
data:
  eno-ws.properties: |-
    #############  Swagger host #############
    fr.insee.enows.api.scheme=https
    fr.insee.enows.api.host=eno-example.com

    ############# Logging #############
    logging.config=${catalina.base}/webapps/log4j2.xml
